# Generated by Django 4.0.5 on 2022-06-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_hood_delete_neighborhood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hood',
            new_name='Neighborhood',
        ),
    ]
