# Generated by Django 4.0.5 on 2022-06-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0007_remove_neighborhood_population_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
    ]
